### ISSUE TITLE
navigator.app.exitApp() crashes when using cordova-certificate-plugin

### ISSUE THREAD

**Issue by Fmstrat** [hypery2k/cordova-certificate-plugin#3]
This works, and after about one second the app exits cleanly:

```
onDeviceReady: function() {
    init();
    setTimeout(function() { navigator.app.exitApp(); }, 1000);
},
```

However, this crashes and pops up the "quit unexpectedly" message in Android:

```
onDeviceReady: function() {
    init();
    cordova.plugins.certificates.trustUnsecureCerts(true);
    setTimeout(function() { navigator.app.exitApp(); }, 1000);
},
```

With this in the logcat:

```
D/CordovaActivity( 2561): onMessage(exit,null)
D/CordovaActivity( 2561): Paused the application!
W/PluginManager( 2561): THREAD WARNING: exec() call to App.exitApp blocked the main thread for 90ms. Plugin should use CordovaInterface.getThreadPool().
D/CordovaActivity( 2561): CordovaActivity.onDestroy()
D/CordovaWebView( 2561): >>> loadUrlNow()
D/CordovaWebViewClient( 2561): onPageFinished(about:blank)
D/AndroidRuntime( 2561): Shutting down VM
W/dalvikvm( 2561): threadid=1: thread exiting with uncaught exception (group=0xb0d58b20)
E/AndroidRuntime( 2561): FATAL EXCEPTION: main
E/AndroidRuntime( 2561): Process: com.mycomp.myapp, PID: 2561
E/AndroidRuntime( 2561): java.lang.NullPointerException
E/AndroidRuntime( 2561):        at org.apache.cordova.CordovaWebViewClient.onPageFinished(CordovaWebViewClient.java:215)
E/AndroidRuntime( 2561):        at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:449)
E/AndroidRuntime( 2561):        at com.android.org.chromium.android_webview.AwContentsClient$AwWebContentsObserver$1.run(AwContentsClient.java:73)
E/AndroidRuntime( 2561):        at android.os.Handler.handleCallback(Handler.java:733)
E/AndroidRuntime( 2561):        at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime( 2561):        at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime( 2561):        at android.app.ActivityThread.main(ActivityThread.java:5017)
E/AndroidRuntime( 2561):        at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime( 2561):        at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime( 2561):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
E/AndroidRuntime( 2561):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
E/AndroidRuntime( 2561):        at dalvik.system.NativeStart.main(Native Method)
I/Process ( 2561): Sending signal. PID: 2561 SIG: 9
I/ActivityManager( 1276): Process com.mycomp.myapp (pid 2561) has died.
```

Everything else works fine, it just crashes when you try to implement code to exit the application, such as on back button press. Any thoughts?

**Comment by hypery2k** [comment]
I will add some tests for investigating this

**Comment by escapedcat** [comment]
For me the Android app crashes as well, when I do a `window.location.reload()`
Seems to be similar to this one.

**Comment by hypery2k** [comment]
seems no error at my classes so please retry with latest version and cordova-android version and report as new issue with more version details.

For me it's working
